language:
- php
- c

php:
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- sudo apt-get install php5-dev libpcre3-dev gcc make
- cd build
- ./install 
- cd ..


script:  phpunit --configuration test/phpunit.xml --process-isolation


notifications:
  email: false